export const ru = {
  app: {
    library: "Библиотека",
    addGame: "Добавить игру",
    all: "Все",
    searchLibrary: "Поиск по библиотеке",
    noGamesFound: "Игры не найдены",
    friends: "Друзья",
    online: "Онлайн",
    add: "Добавить",
    addFriendsHint: "Добавьте друзей по friend code",
    invite: "Пригласить",
    settings: "Настройки",
    addGameToStart: "Добавьте игру, чтобы начать",
    addCover: "Добавить обложку",
    change: "Изменить",
    remove: "Удалить",
    lastPlayed: "Последний запуск",
    totalPlayTime: "Общее время",
    play: "Играть",
    solo: "Соло",
    room: "Комната",
    networkLine: "Сеть",
    roomCode: "Код комнаты",
    roomConnected: "Подключено",
    roomNotConnected: "Не подключено",
    createRoom: "Создать комнату",
    closeRoom: "Закрыть комнату",
    join: "Войти",
    overview: "Обзор",
    network: "Сеть",
    replays: "Повторы",
    localReady: "Локальный запуск готов. Для комнаты используйте вкладку Сеть.",
    signalingUrlCurrent: "Текущий URL сервера сигналинга",
    modeCurrent: "Текущий режим",
    replayEnabled: "Повторы",
    replayHotkey: "Горячая клавиша",
    replayPrebuffer: "Пре-буфер",
    openReplayFolder: "Открыть папку повторов",
    inviteText: "пригласил вас в комнату",
    accept: "Принять",
    decline: "Отклонить",
    copy: "Копировать",
    never: "Никогда",
    unknown: "Неизвестно",
    min: "мин",
    hourShort: "ч",
    waitingRoomCode: "Введите код комнаты",
    roomNotFound: "Комната не найдена",
    failedCreateRoom: "Не удалось создать комнату",
    failedInvite: "Не удалось отправить приглашение",
    friendCodeNotFound: "Friend code не найден",
    roomStateUnavailable: "Состояние комнаты недоступно",
    hostOnlyStart: "Только хост может запустить сессию",
    launchPrecheckFailed: "Предпроверка запуска не пройдена",
    gameNotLaunchable: "Игра не может быть запущена",
    streamNeedsOneGuest: "Для stream-режима нужен ровно один гость в комнате",
    failedStartStream: "Не удалось запустить stream-режим",
    failedStartNetplay: "Не удалось запустить netplay",
    gameMenuTitle: "Меню игры",
    gameMenuContinue: "Продолжить",
    gameMenuPause: "Пауза",
    gameMenuResume: "Снять паузу",
    gameMenuSaveState: "Сохранить (F5)",
    gameMenuLoadState: "Загрузить (F9)",
    gameMenuSoundOn: "Звук: Вкл",
    gameMenuSoundOff: "Звук: Выкл",
    gameMenuSettings: "Настройки",
    gameMenuExit: "Выйти",
    gamePausedBySettings: "Пауза: открыты настройки",
    gamePausedByYou: "Пауза: вы",
    gamePausedByPeer: "Пауза: второй игрок",
    selectGame: "Выберите игру",
    failedUpdateEmulator: "Не удалось обновить эмулятор",
    launchFailed: "Не удалось запустить игру",
    streamModeLabel: "Потоковый режим",
    inputSyncLabel: "Синхронизация кнопок",
    selectGameInLibrary: "Выберите игру в библиотеке"
  },
  settings: {
    title: "Настройки",
    close: "Закрыть",
    general: "Общие",
    controls: "Управление",
    video: "Видео",
    audio: "Аудио",
    network: "Сеть",
    library: "Библиотека",
    about: "О приложении",
    steamLike: "Steam-подобный интерфейс. Настройки сохраняются в userData.",
    preset: "Профиль",
    keyboard: "Клавиатура",
    gamepad: "Геймпад",
    rebind: "Назначить",
    resetDefaults: "Сброс по умолчанию",
    snesControls: "Управление SNES",
    snesHint: "Крестовина: стрелки/WASD | B: J | A: K | Y: U | X: I | L: Q | R: E | Start: Enter | Select: Right Shift/Tab",
    scale: "Масштаб",
    pixelMode: "Пиксельный режим",
    crt: "CRT",
    vignette: "Виньетка",
    colorCorrection: "Цветокоррекция",
    previewNote: "Изменения применяются к игровому canvas сразу.",
    recordingReplay: "Запись / Повтор",
    enableReplay: "Включить повторы",
    hotkey: "Горячая клавиша",
    prebufferSeconds: "Секунды пре-буфера",
    quality: "Качество",
    fps: "FPS",
    format: "Формат",
    saveFolder: "Папка сохранения",
    openReplayFolder: "Открыть папку повторов",
    resetReplaySettings: "Сбросить настройки повторов",
    sound: "Звук",
    on: "Вкл",
    off: "Выкл",
    volume: "Громкость",
    latency: "Задержка (мс)",
    signalingServer: "Сервер сигналинга",
    connect: "Подключить",
    netplayMode: "Режим netplay",
    streaming: "Хороший интернет (поток)",
    lockstep: "Плохой интернет (синхронизация кнопок)",
    showPlatformBadges: "Показывать бейджи платформ в библиотеке",
    aboutText: "NES/SNES Netplay Emulator, интерфейс в стиле Steam."
  }
} as const;

export type TranslationMap = typeof ru;
