export const ru = {
  app: {
    library: "Library",
    addGame: "Add game",
    all: "All",
    searchLibrary: "Search library",
    noGamesFound: "No games found",
    friends: "Friends",
    online: "Online",
    add: "Add",
    addFriendsHint: "Add friends by friend code",
    invite: "Invite",
    settings: "Settings",
    addGameToStart: "Add a game to start",
    addCover: "Add cover",
    change: "Change",
    remove: "Remove",
    lastPlayed: "Last launch",
    totalPlayTime: "Total play time",
    play: "Play",
    solo: "Solo",
    room: "Room",
    networkLine: "Network",
    roomCode: "Room code",
    roomConnected: "Connected",
    roomNotConnected: "Not connected",
    createRoom: "Create room",
    closeRoom: "Close room",
    join: "Join",
    overview: "Overview",
    network: "Network",
    replays: "Replays",
    localReady: "Local launch is ready. Use the Network tab for room mode.",
    signalingUrlCurrent: "Current signaling URL",
    modeCurrent: "Current mode",
    replayEnabled: "Replays",
    replayHotkey: "Hotkey",
    replayPrebuffer: "Pre-buffer",
    openReplayFolder: "Open replays folder",
    inviteText: "invited you to a room",
    accept: "Accept",
    decline: "Decline",
    copy: "Copy",
    never: "Never",
    unknown: "Unknown",
    min: "min",
    hourShort: "h",
    waitingRoomCode: "Enter room code",
    roomNotFound: "Room not found",
    failedCreateRoom: "Failed to create room",
    failedInvite: "Failed to send invite",
    friendCodeNotFound: "Friend code not found",
    roomStateUnavailable: "Room state unavailable",
    hostOnlyStart: "Only host can start session",
    launchPrecheckFailed: "Launch precheck failed",
    gameNotLaunchable: "Game cannot be launched",
    streamNeedsOneGuest: "Stream mode requires exactly one guest",
    failedStartStream: "Failed to start stream mode",
    failedStartNetplay: "Failed to start netplay",
    gameMenuTitle: "Game menu",
    gameMenuContinue: "Continue",
    gameMenuPause: "Pause",
    gameMenuResume: "Resume",
    gameMenuSaveState: "Save (F5)",
    gameMenuLoadState: "Load (F9)",
    gameMenuSoundOn: "Sound: On",
    gameMenuSoundOff: "Sound: Off",
    gameMenuSettings: "Settings",
    gameMenuExit: "Exit",
    gamePausedBySettings: "Paused: settings opened",
    gamePausedByYou: "Paused: you",
    gamePausedByPeer: "Paused: second player",
    selectGame: "Select a game",
    failedUpdateEmulator: "Failed to update emulator",
    launchFailed: "Failed to launch game",
    streamModeLabel: "Streaming mode",
    inputSyncLabel: "Input sync",
    selectGameInLibrary: "Select a game in library"
  },
  settings: {
    title: "Settings",
    close: "Close",
    general: "General",
    controls: "Controls",
    video: "Video",
    audio: "Audio",
    network: "Network",
    library: "Library",
    about: "About",
    steamLike: "Steam-like interface. Settings are stored in userData.",
    preset: "Preset",
    keyboard: "Keyboard",
    gamepad: "Gamepad",
    rebind: "Rebind",
    resetDefaults: "Reset defaults",
    snesControls: "SNES controls",
    snesHint: "D-pad: arrows/WASD | B: J | A: K | Y: U | X: I | L: Q | R: E | Start: Enter | Select: Right Shift/Tab",
    scale: "Scale",
    pixelMode: "Pixel mode",
    crt: "CRT",
    vignette: "Vignette",
    colorCorrection: "Color correction",
    previewNote: "Changes are applied to game canvas instantly.",
    recordingReplay: "Recording / Replay",
    enableReplay: "Enable replays",
    hotkey: "Hotkey",
    prebufferSeconds: "Pre-buffer seconds",
    quality: "Quality",
    fps: "FPS",
    format: "Format",
    saveFolder: "Save folder",
    openReplayFolder: "Open replay folder",
    resetReplaySettings: "Reset replay settings",
    sound: "Sound",
    on: "On",
    off: "Off",
    volume: "Volume",
    latency: "Latency (ms)",
    signalingServer: "Signaling server",
    connect: "Connect",
    netplayMode: "Netplay mode",
    streaming: "Good internet (stream)",
    lockstep: "Poor internet (input sync)",
    showPlatformBadges: "Show platform badges in library",
    aboutText: "nes netplay online, Steam-style interface."
  }
} as const;

export type TranslationMap = typeof ru;
